version: "3"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:15-alpine
    container_name: task-lib
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
